### ISSUE TITLE
nftables::set can only be assigned to 1 table

### ISSUE THREAD

**Issue by AlexSamad** [voxpupuli/puppet-nftables#100]
Hi

I have a set of sets that I want to use in my 
inet filter table as well as my ip nat table

the class only takes 1 table as input and as its not part of the title I can only have 1 

nftables::set{ 'management_ip':
...
table => 'STRING' 
}

maybe if it took an array of string.

**Comment by nbarrientos** [comment]
Hi @AlexSamad 

Thanks for the suggestion. I've submitted a change request covering your request :)
