### ISSUE TITLE
extending the title of chains to include table 

### ISSUE THREAD

**Issue by AlexSamad** [voxpupuli/puppet-nftables#101]
Hi

I'm in the process of trying to get docker.io ce and kube working with rhel8 and puppet.
The issue is that docker wants a certain set of tables / chains setup with specific names.

Docker has made the change to using nft over iptables.

But the issue is that it wants specific able names setup - it adds to this it doesn't create its own or allow you to specific a table  / chain name.

What they expect is that the old setup under iptables is replicated out to nft tables.

I can do this with nft tables, but I can't do it easily with this module. you guys made changes changes for the default table setup - thanks.
Would be nice if you could update the epp file that creates puppet.nft file to include those tables... but I have used custom-* to work around that.

So for example in iptables, INPUT OUTPUT is used in all 3 tables space (filter, nat, mangle)
I can't represent that, I use custom right now to create them. 

But i would like to use nft puppet module to manage it completely

So I am thinking it would be nice to extend the nftables::chain title to be the same as the other resource you have so 
<table>-<chain name>. I guess in theory I could name the title unique and overwrite the chain attribute - but it would make it the same as the other resource definitions you have.

Also - can  I add this here or in another ticket
Working with servers that have docker and kue installed means even though I want to update nft / firewall / iptables from puppet I would like the option to set a flag so that the new rules are tested and then put in place - as in the /etc/nft/puppet/  but you don't try and enable the nft ruleset and there is no way to preserve the kube/docker rules

Plus I have found (in iptables, haven't tested nft), but when you flush iptables it clears the connection table and suddenly all of your est connections are allowed through - especially if you have a allow rules which are limited to syn packets or related flows

Also (3rd one :) )  with the flush option, would be nice to say / or have a option that says flush only known tables - ones that are defined by nft module - you have this info in facts.

So the options could be 
flush all
flush all except <x> ## this is the option you have 
flush only managed ## new 

thanks

**Comment by nbarrientos** [comment]
I'm talking rubbish, you can add chains with repeated names to other tables as the code stands today. For instance, to add the chain `INPUT` (which is also present in `inet filter`) to `ip nat`, declare:

```puppet
  nftables::chain{'nat_input':
    chain => 'INPUT',
    table => 'ip-nat'
  }
```

The type only [uses the resource title as default,](https://github.com/voxpupuli/puppet-nftables/blob/master/manifests/chain.pp#L5) but always honors the `chain` parameter to create the concats.

We could if needed though change the resource titles of the chains declared in `inet_filter.pp` and `ip_nat.pp` so they don't monopolize the namespace.

**Comment by AlexSamad** [comment]
Hi

Okay if the resource name is a default, then you are correct.
Apologies didn't think of that

A

**Comment by nbarrientos** [comment]
@AlexSamad can this be closed?
