### ISSUE TITLE
Publish to forge.puppet.com

### ISSUE THREAD

**Issue by nbarrientos** [voxpupuli/puppet-nftables#11]
We could add the module to the [Puppet forge](https://forge.puppet.com/upload). Make sure first that the metadata is correctly filled before doing it (I think that all data is consumed automatically from `metadata.json`).

**Comment by duritong** [comment]
I would only like to do it, if we can do the push directly out of travis-ci, so we only need to flip the module version

**Comment by nbarrientos** [comment]
Makes sense, publishing when tagging a version sounds reasonable.

https://docs.travis-ci.com/user/deployment/puppetforge/

Personally I've never used it.

**Comment by duritong** [comment]
Also relevant:
* https://voxpupuli.org/docs/publish_setup/


I added an encrypted token to my forge account to the `.travis.yml` - but still commented out. it is available here: #21

**Comment by traylenator** [comment]
I'll refresh the REFERENCE now before any publish is made.

**Comment by duritong** [comment]
Depending on how #35 goes, this might become obsolete.

**Comment by duritong** [comment]
obsolete
