### ISSUE TITLE
Use of actual Protocol Numbers instead of aliases?

### ISSUE THREAD

**Issue by herbetom** [voxpupuli/puppet-nftables#111]
I'm not a user of this project. I was just searching for a OSPF v3 rule for nftables and found this repo. 

https://github.com/voxpupuli/puppet-nftables/blob/f82aaa5a6058f50e0af23db75a17276cf19dfb60/manifests/rules/ospf3.pp#L5

https://github.com/voxpupuli/puppet-nftables/blob/f82aaa5a6058f50e0af23db75a17276cf19dfb60/manifests/rules/out/ospf3.pp#L5

Hoewer those two lines didn't work because my system isn't recognizing the protocol name:

```
Nov 17 04:10:48 zeus nft[721544]: /etc/nftables.conf:67:67-70: Error: Could not resolve protocol name
Nov 17 04:10:48 zeus nft[721544]:                 ip6 saddr fe80::/64 ip6 daddr { ff02::5, ff02::6 } meta l4proto ospf accept
Nov 17 04:10:48 zeus nft[721544]:                                                                                 ^^^^
```
My system info:

```
[tom@zeus ~]$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.1.6
Codename:       Pahvo
[tom@zeus ~]$ uname -a
Linux zeus 5.14.10-1-MANJARO #1 SMP PREEMPT Thu Oct 7 06:43:34 UTC 2021 x86_64 GNU/Linux
[tom@zeus ~]$ nft -v
nftables v1.0.0 (Fearless Fosdick #2)
```

I tried it with `meta l4proto 89` and it's valid and on the first glance seems to work. After that i took a look at `nft list ruleset` and the rule is shown as `meta l4proto ospfigp`. Perhaps it is more universal to use the actual protocol number, even if it's harder to read? 
If those aliasses aren't universal the only other idea (besides ignoring it) would be to create a mapping. That sounds even worse.

I just wanted to leave a comment. Feel free to ignore it, close it, ... especically because the default Issue template wasn't really a good fit for this. Sorry about that. :sweat_smile:

cc @keachi (reason: introduction of those ospf rules: https://github.com/voxpupuli/puppet-nftables/commit/ba5e15bd56e83c7402e0c7901c845a25a7996206)

**Comment by keachi** [comment]
Thank you @herbetom for this report! Seems legit to me to switch to the protocol number. Prior it was l4proto ospf, but I guess there is a switch to ospfigp, therefore switching to the protocol number would be a good idea.

My system (CentOS Stream 8):
```
~> uname -a
Linux localhost.localdomain 4.18.0-348.el8.x86_64 #1 SMP Tue Oct 19 15:14:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
~> nft -v
nftables v0.9.3 (Topsy)
```
And my OSPF rule:
```
iifname enp1s0 ip6 saddr fe80::/64 ip6 daddr { fe80::/64, ff02::5-ff02::6 } meta l4proto ospf accept
```

**Comment by nbarrientos** [comment]
Personally, I'd be more in favor of changing stuff once the module declares compatibility in code for other operating systems. Officially, at the moment it's only supported on [operating systems of the RedHat family](https://github.com/voxpupuli/puppet-nftables/blob/master/metadata.json#L30). If the module ever asserted Manjaro compatibility the functional tests that include all the predefined rules will automatically fail, discovering all the protocol aliases that don't work. Just my two cents.

**Comment by keachi** [comment]
The protocol is named `ospf` in Red Hat based systems (see [/etc/protocols](https://pagure.io/setup/blob/master/f/protocols#_105)). IANA names the protocol OSPFIGP (see [protocol-numbers.xml](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xml).

**Comment by herbetom** [comment]
For what it's worth, in Debian Bullsyes it also seems to be `ospf`. I don't know where the line is, but I personally wouldn't expect either side to drop the current name in the future without keeping the old one as a fallback. 
So it should be okay to change nothing for the time being. :shrug:
