### ISSUE TITLE
Incomplete forward chain rules for docker_ce

### ISSUE THREAD

**Issue by glpatcern** [voxpupuli/puppet-nftables#114]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.20
- Ruby:
- Distribution: CentOS Stream 8
- Module version:

## How to reproduce (e.g Puppet code you use)

1. (Behind CERN login) https://gitlab.cern.ch/ai/it-puppet-hostgroup-box/-/blob/qa/code/manifests/wopi.pp#L98-L109
2. A docker-compose setup with multiple containers and a custom network

## What are you seeing

Docker containers do not see each other, nftables logs rejected traffic.

## What behaviour did you expect instead

Seamless networking

## Output log

```
2021-12-06T15:28:47.648098+01:00 cbox-appsdev-01.cern.ch kernel: [nftables] FORWARD Rejected: IN=br-ea660202f5a0 OUT=eth0 PHYSIN=vethbd4a68f MACSRC=xxxxxx MACDST=xxxxxx MACPROTO=0800 SRC=172.19.0.2 DST=x.x.x.x LEN=56 TOS=0x00 PREC=0x00 TTL=63 ID=19185 DF PROTO=UDP SPT=54587 DPT=53 LEN=36 
```

## Any additional information you'd like to impart

The same configuration works fine on a CentOS 7 host with `iptables` and the following extra rules in puppet terms:
```
       firewall { '001 Accept established for docker':
            chain  => 'FORWARD',
            state  => ['RELATED', 'ESTABLISHED'],
            proto  => 'all',
            action => 'accept',
        }

        firewall { '002 Forward to docker':
            chain  => 'FORWARD',
            proto  => 'all',
            jump   => 'DOCKER',
        }
```

Therefore it seems the `::nftables::rules::docker_ce` are incomplete.

**Comment by traylenator** [comment]
Please provide the steps to reproduce here as well.

**Comment by glpatcern** [comment]
In first approximation the nftables logs and the corresponding legacy rules should help, otherwise I guess it's quicker to give you access to a box where this is configured rather than for you trying to boot up my network of containers (or me creating a mock docker config from scratch)

**Comment by nbarrientos** [comment]
Hi @glpatcern

As stated in the header/docs, the configuration distributed in this class represents the default firewall configuration done by docker-ce when the iptables integration is enabled. 

I've deployed this simple configuration:

```puppet
  $_dockermirror = 'http://linuxsoft.cern.ch/mirror/download.docker.com'

  class { 'docker':
    docker_ce_package_name      => 'docker-ce',
    docker_ce_source_location   => "${_dockermirror}/linux/centos/${::facts['os']['release']['major']}/x86_64/stable",
    iptables                    => false
  }

  include ::nftables::rules::docker_ce
```

Which uses the default bridged network configuration that this class expects (`docker0` as bridge interface and `"172.17.0.0/16"` as subnet), and created two containers as follows:

```
docker run -it --rm alpine /bin/sh
```

which were assigned addresses `172.17.0.3` and `172.17.0.2` and both can see each other (tested sending both ICMP and TCP traffic using `nc -l` on one side and `nc` on the other).

If you use custom networks (via `docker` directly or via `docker-compose`) you might have to tweak these class parameters:

* `nftables::rules::docker_ce::docker_interface`
* `nftables::rules::docker_ce::docker_prefix`

or even, depending on how exotic your configuration is, this class might not be of any use for you and you'll have to deploy your firewall manually using more basic building blocks like `nftables::rule` et al.

**Comment by glpatcern** [comment]
> * nftables::rules::docker_ce::docker_prefix

That was it, thanks @nbarrientos. I may even suggest to set `172.16.0.0/12` as default to capture all custom networks in the official `172.x.x.x` private IPs range. But my fix (i.e. specifying the above in my config) is good enough.

**Comment by glpatcern** [comment]
Actually, still related to this issue: I see I have no DNS resolution from within the containers, and symptoms from the host are the following output from `ip route`:
```
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 metric 425 linkdown 
```
As well as the nftables logs reporting UDP traffic rejected.

Could it be that the `docker_prefix` option reconfigures TCP traffic only and not UDP?

**Comment by nbarrientos** [comment]
WFM:

```
...
# docker network inspect 6c4f65673ee0
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
...
        "Containers": {
            "8e7728704658618c1fbd058533c13620545e12db41d09a94ec0341d58efbed29": {
                "Name": "gracious_newton",
                "EndpointID": "feb843558accea5d0723ab275f085bfc807a4d85704a69dfb8afdaec0a8386fc",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
```

```
# docker run -it --rm alpine /bin/sh
/ # nslookup github.com
Server:		foo
Address:	foo:53

Non-authoritative answer:

Non-authoritative answer:
Name:	github.com
Address: 140.82.121.3
```

The traffic is correctly sent out by the masquerade rule in table `nat`, chain `POSTROUTING` and the response delivered back to the container:

```
14:37:46.525049 IP (tos 0x0, ttl 64, id 52617, offset 0, flags [DF], proto UDP (17), length 56)
    172.17.0.2.41448 > foo.domain: 14418+ A? github.com. (28)
14:37:46.525130 IP (tos 0x0, ttl 64, id 52618, offset 0, flags [DF], proto UDP (17), length 56)
    172.17.0.2.41448 > foo.cern.ch.domain: 14841+ AAAA? github.com. (28)
14:37:46.525320 IP (tos 0x0, ttl 62, id 24419, offset 0, flags [none], proto UDP (17), length 140)
    foo.domain > 172.17.0.2.41448: 14841 0/1/0 (112)
14:37:46.525377 IP (tos 0x0, ttl 62, id 24420, offset 0, flags [none], proto UDP (17), length 535)
    foo.domain > 172.17.0.2.41448: 14418 1/8/12 github.com. A 140.82.121.3 (507)
```

**Comment by glpatcern** [comment]
> WFM:

Thanks Nacho, but: sure it works with the default `172.17.0.0/16` subnet, not in the customized `172.16.0.0/12` one. That's why I suggested it could be how the `docker_prefix` option is taken into account. The signature in the nftables log is pretty clear:

```
2021-12-09T14:10:21.813083+01:00 cbox-appsdev-01.cern.ch kernel: [nftables] FORWARD Rejected: IN=br-ea660202f5a0 OUT=eth0 PHYSIN=veth34306e6 MACSRC=02:42:ac:13:00:04 MACDST=02:42:2c:9a:05:07 MACPROTO=0800 SRC=172.19.0.4 DST=137.138.17.5 LEN=49 TOS=0x00 PREC=0x00 TTL=63 ID=11023 DF PROTO=UDP SPT=56292 DPT=53 LEN=29 
```

Again happy to give you access to the box for you to avoid creating a docker-compose network.

**Comment by nbarrientos** [comment]
The name of the interface of your bridge is `br-ea660202f5a0`, which differs from the default (`docker0`). Could you please customise it (and I'd recommend to fix the name [0], too) using the instructions provided [here](https://github.com/voxpupuli/puppet-nftables/issues/114#issuecomment-986935757) (`nftables::rules::docker_ce::docker_interface`)?

[0]
```yaml
networks:
  test-net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: whatever
    driver_opts:
      com.docker.network.bridge.name: br_name
```

**Comment by glpatcern** [comment]
For reference, this is fixed by creating the custom network with:
```
docker network create -o "com.docker.network.bridge.name=docker1" <your-network>
```
executed on the host. You can't change the custom network from the d-c configuration.

Only then, the `nftables::rules` customization can be applied. Still puzzled that so much has to be done whereas the old firewall rules would work with any `br-xxx` network interface.
