### ISSUE TITLE
how open are we to new rules?

### ISSUE THREAD

**Issue by anarcat** [voxpupuli/puppet-nftables#164]
Hi!

Before flooding this project with PRs, I figured I would ask first:

How open are we to adding more rules to the module?

I already wrote two classes for Syncthing and Avahi, which are useful on workstations... And I expect I'll come up with plenty more in the future! Is the current set static or are users expected to provide their own ideas?

Or should we just write our own stuff in our private profiles?

They are fairly trivial things, I must say... but not so different from other things already in the module. For example, my avahi class is basically `nftables::rules::afs3_callback` with port 5353 instead of 7001, and syncthing is just `tcp dport 22000 accept`...

Thanks!

**Comment by traylenator** [comment]
Adding new rules for services which run at more that one site is very welcome.

Go for it I would say.
