### ISSUE TITLE
Get it under the voxpupuli umbrella

### ISSUE THREAD

**Issue by duritong** [voxpupuli/puppet-nftables#35]
We agreed on trying to submit the module under the voxpupuli umbrella

https://voxpupuli.org/docs/migrate_module/

@traylenator seems to have some experience with it.

**Comment by traylenator** [comment]
Don't think there is much point publishing to forge  before migration as it will only require the old namespace version to be deprecated.



https://voxpupuli.org/docs/migrate_module/

Is the procedure.

So I can ask for you to be added to the incoming-modules group.

**Comment by traylenator** [comment]
@duritong you should now have permissions to move this repo to voxpupuli name space.

This will move also curent MR and issues also.

The instructions above are slightly wrong in that github pipelines are now being used rather than travis so the travis hook should not be left enabled.

**Comment by duritong** [comment]
moved

**Comment by traylenator** [comment]
Thanks - Submitting plumbing and module sync templates now....

**Comment by traylenator** [comment]
modulesync'd branch now in voxpupuli master.

Still some plumbing to do before release but fine for new merges now.
