### ISSUE TITLE
Dismiss stale pull request approvals when new commits are pushed

### ISSUE THREAD

**Issue by nbarrientos** [voxpupuli/puppet-nftables#61]
Dunno if this is voxpupuli's policy but it seems that this setting is not enabled in this repository:

![image](https://user-images.githubusercontent.com/131893/104902812-798e0000-597f-11eb-8c30-76b2ca2582f1.png)

Would it reasonable to enable it? In my opinion it makes sense to reset approvals if new code is pushed to a change request.

Relevant docs: https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

**Comment by duritong** [comment]
Yeah, although sometimes I approve with a minor type in question. Which means for a simple spell check correction I'll have to re-approve, but probably less harmful than additional code that gets pushed and not reviewed.

**Comment by nbarrientos** [comment]
@bastelfreak Any input from the voxpupuli's side?

**Comment by bastelfreak** [comment]
hi,
I enabled it for this repo

**Comment by bastelfreak** [comment]
I'm not 100% sure, but maybe our release process breks if reviews are enforced and that's why we didn't enable it some time ago. In case it fails we can disable the approval settings again.

**Comment by traylenator** [comment]
Yes release process broken.

```
 bundle exec rake travis_release
Cleaning for module build
Bumping version from 1.1.1 to 1.1.2-rc0
rake aborted!
Blacksmith::Error: Command ["git", "--git-dir", "/tmp/puppet-nftables/.git", "--work-tree", "/tmp/puppet-nftables", "push"] failed with exit status pid 67553 exit 1
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To github.com:voxpupuli/puppet-nftables.git
```

Think the tag is pushed with the rc commit as well ? So the release never happens. Pushing the 1.1.1 semi-manually.
