### ISSUE TITLE
Add support for Debian

### ISSUE THREAD

**Issue by kienanstewart** [voxpupuli/puppet-nftables#65]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Ruby: 2.5
- Distribution: Debian Buster
- Module version: 1.0.0

## Description

There are a few changes to make the module work on Debian

 * the nftables configuration file should /etc/nftables.conf instead of /etc/sysconfig/nftables.conf
 * the directory /etc/nftables is not created by the Debian package for nftables (managing it in the module would work?)
 * firewalld is not installed by default, so should be `false` instead of `mask` on Debian systems by default
 * (optional) for Debian Stretch, the version of facter shipped w/ the OS does not use structured facts. If it is desired to extend support to Debian Stretch, that case should be handled as well.
 
I have a WIP branch dev for which I will open a PR.

thanks

**Comment by Leeloo5E** [comment]
I would be very interested in this being incorporated. Debian is also a widely used distribution.
Can you foresee when things will go ahead here?

**Comment by duritong** [comment]
When people continue to push things on the outstanding pull request and make it possible to merge: #66 . This is a free software project and not a product, if you want something in either contribute or wait (patiently). Thank you.

**Comment by Leeloo5E** [comment]
Sorry, that was more of a hint in the direction of whoever opened the pull request and request.
If someone started it, maybe they should finish it.
Alternatively, of course, you can do it yourself or, as you write, wait ... Let's see what happens.

**Comment by geor-g** [comment]
I believe that's done via https://github.com/voxpupuli/puppet-nftables/pull/134.
