### ISSUE TITLE
Class[Nftables::Bridges]['bridgenames'] contains a Regexp value. It will be converted to the String '/^br.+/'

### ISSUE THREAD

**Issue by traylenator** [voxpupuli/puppet-nftables#83]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.20.0

Noticed in our puppetserver logs:

```
2021-03-23T07:28:07.219+01:00 WARN  [qtp1376093148-42] [puppetserver] Puppet Class[Nftables::Bridges]['bridgenames'] contains a Regexp value. It will be converted to the String '/^br.+/'
```

**Comment by duritong** [comment]
I don't understand the issue. It should be a regexp and it also is: https://github.com/voxpupuli/puppet-nftables/blob/18b211e72a046db71acda7bf2fad8144b9e72e8b/manifests/bridges.pp#L5

Why is it complaining?

**Comment by traylenator** [comment]
Agree , i can't see what might be wrong if anything.

**Comment by traylenator** [comment]
https://tickets.puppetlabs.com/browse/PUP-7735 gives some insight.

**Comment by duritong** [comment]
Can't reproduce it with the example:

```
# puppet apply foo.pp
Notice: Scope(Class[main]): Regexp[/^.$/]
Notice: Scope(Class[Foo]): Regexp[/^.$/]
Notice: Compiled catalog for xyz in environment production in 0.02 seconds
Notice: Applied catalog in 0.30 seconds
# puppet --version
7.5.0
```

And I also don't see it in our puppetserver logs.

**Comment by traylenator** [comment]
@duritong that's with a Puppet 7 you do not see message ? If so suggest we ignore.

**Comment by traylenator** [comment]
Ignoring as apparently not present in newer puppets.
